version: "3.9"

services:
  traefik:
    image: traefik:v3.1
    container_name: condos-traefik
    command:
      - "--api.dashboard=true"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Redirección de HTTP → HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # Proveedor dinámico
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

      # Let's Encrypt
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=jolvera70@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/acme.json"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/traefik_dynamic.yml:/etc/traefik/dynamic/traefik_dynamic.yml:Z
      - ./acme.json:/acme.json

  mongo:
    image: mongo:6
    container_name: ${PROJECT_NAME:-condos}-mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: app_user
      MONGO_INITDB_ROOT_PASSWORD: app_passT3st
      MONGO_INITDB_DATABASE: condos
    volumes:
      - ./volumes/mongo:/data/db:Z
      - ./mongo-init:/docker-entrypoint-initdb.d:ro,Z

  minio:
    image: quay.io/minio/minio:latest
    container_name: ${PROJECT_NAME:-condos}-attachments
    command: server /data --console-address ":9001"
    ports: ["9000:9000","9001:9001"]
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin12345
    volumes:
      - ./minio-data:/data

  auth-api:
    build: ./auth-api
    container_name: ${PROJECT_NAME}-auth-api
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://app_user:app_passT3st@mongo:27017/condos?authSource=admin"
      SPRING_PROFILES_ACTIVE: "dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  tenant-api:
    build: ./tenant-api
    container_name: ${PROJECT_NAME}-tenant-api
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://app_user:app_passT3st@mongo:27017/condos?authSource=admin"
      SPRING_PROFILES_ACTIVE: "dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  user-api:
    build: ./user-api
    container_name: ${PROJECT_NAME}-user-api
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://app_user:app_passT3st@mongo:27017/condos?authSource=admin"
      SPRING_PROFILES_ACTIVE: "dev"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  board-api:
    build: ./board-api
    container_name: ${PROJECT_NAME}-board-api
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://app_user:app_passT3st@mongo:27017/condos?authSource=admin"
      SPRING_PROFILES_ACTIVE: "dev"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5

    #task-api:
    #build: ./task-api
    #container_name: ${PROJECT_NAME}-task-api
        #labels:
        #- "traefik.enable=true"
        #- "traefik.http.routers.task.rule=PathPrefix(`/me/task`)"
      #- "traefik.http.services.task.loadbalancer.server.port=${SPRING_PORT}"
      #healthcheck:
      #test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health"]
      #interval: 10s
      #timeout: 3s
      #retries: 5

networks:
  default:
    name: ${NETWORK_NAME}