server:
  port: 8088

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/condos}

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.condos: DEBUG

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html
  api-docs.enabled: true
  swagger-ui.enabled: true